name: Release

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  release:

    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            git clone git@github.com:algao1/miniploy.git
            cd miniploy
            task run
            echo "Deployment successful!"